2024-04-09 13:55:22,347 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Configure stats pid to 18140
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Loading settings from C:\Users\YouTianyu\.config\wandb\settings
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Loading settings from D:\workspace\code\cdvae\wandb\settings
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'start_method': 'thread', 'root_dir': 'D:/workspace/code/cdvae/wabdb'}
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 13:55:22,348 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'cdvae\\run.py', 'program_abspath': 'd:\\workspace\\Code\\cdvae\\cdvae\\run.py', 'program': 'd:/workspace/Code/cdvae/cdvae/run.py'}
2024-04-09 13:55:22,349 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 13:55:22,349 INFO    MainThread:18140 [wandb_setup.py:_flush():76] Applying login settings: {'mode': 'offline'}
2024-04-09 13:55:22,349 INFO    MainThread:18140 [wandb_init.py:_log_setup():521] Logging user logs to .\wandb\run-20240409_135522-49q72rw2\logs\debug.log
2024-04-09 13:55:22,349 INFO    MainThread:18140 [wandb_init.py:_log_setup():522] Logging internal logs to .\wandb\run-20240409_135522-49q72rw2\logs\debug-internal.log
2024-04-09 13:55:22,349 INFO    MainThread:18140 [wandb_init.py:init():561] calling init triggers
2024-04-09 13:55:22,350 INFO    MainThread:18140 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-09 13:55:22,350 INFO    MainThread:18140 [wandb_init.py:init():611] starting backend
2024-04-09 13:55:22,350 INFO    MainThread:18140 [wandb_init.py:init():615] setting up manager
2024-04-09 13:55:22,359 INFO    MainThread:18140 [wandb_init.py:init():623] backend started and connected
2024-04-09 13:55:22,364 INFO    MainThread:18140 [wandb_init.py:init():715] updated telemetry
2024-04-09 13:55:22,417 INFO    MainThread:18140 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-09 13:55:23,970 ERROR   MainThread:18140 [wandb_init.py:init():774] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-04-09 13:55:24,780 ERROR   MainThread:18140 [wandb_init.py:init():1199] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "D:\miniconda\envs\cdvae\lib\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    run = wi.init()
  File "D:\miniconda\envs\cdvae\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-04-09 13:55:26,992 WARNING MsgRouterThr:18140 [router.py:message_loop():77] message_loop has been closed
